version: '3.8'
services:
  video-editor:
    image: video-editor-app:latest
    container_name: video-editor
    ports:
      - "8080:8080"
    environment:
      - GCS_BUCKET_NAME=shaz-video-editor-bucket
      - GOOGLE_APPLICATION_CREDENTIALS=/app/video-editor-credentials.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./video-editor-credentials.json:/app/video-editor-credentials.json
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G